# Generated by Django 3.0.5 on 2020-04-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
