# Generated by Django 3.0.5 on 2020-04-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0002_auto_20200407_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
