# Generated by Django 3.0.5 on 2020-04-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0003_country_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
