# Generated by Django 3.0.5 on 2020-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0004_auto_20200408_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
