# Generated by Django 3.0.5 on 2020-04-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0005_auto_20200408_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
