# Generated by Django 3.0.5 on 2020-04-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0006_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
