# Generated by Django 3.0.5 on 2020-04-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0007_auto_20200409_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
