# Generated by Django 3.0.5 on 2020-04-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0008_auto_20200409_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
