# Generated by Django 3.0.5 on 2020-04-09 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0009_auto_20200409_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 11, 36, 49, 766246, tzinfo=utc)),
        ),
    ]
