# Generated by Django 3.0.5 on 2020-04-09 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0010_destination_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='date',
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 11, 43, 8, 708143, tzinfo=utc)),
        ),
    ]
