# Generated by Django 3.0.5 on 2020-04-09 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0011_auto_20200409_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 16, 11, 47, 56, 961965, tzinfo=utc)),
        ),
    ]
