# Generated by Django 3.0.5 on 2020-04-25 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0012_auto_20200409_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['travel_date']},
        ),
        migrations.AlterField(
            model_name='destination',
            name='date_completed',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 9, 41, 51, 260497, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dest.Destination')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
