# Generated by Django 3.0.5 on 2020-04-25 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0013_auto_20200425_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='destination',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 11, 42, 55, 471676, tzinfo=utc)),
        ),
    ]
