# Generated by Django 3.0.5 on 2020-05-05 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0015_auto_20200425_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.AddField(
            model_name='destination',
            name='inbound_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='outbound_price',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='destination',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 17, 30, 28, 963651, tzinfo=utc)),
        ),
    ]
