# Generated by Django 3.0.5 on 2020-05-10 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0017_auto_20200510_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 26, 46, 673733, tzinfo=utc)),
        ),
    ]
