# Generated by Django 3.0.5 on 2020-05-10 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0019_auto_20200510_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 56, 3, 374717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
