# Generated by Django 3.0.5 on 2020-05-10 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0020_auto_20200510_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
        migrations.AlterField(
            model_name='destination',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 14, 58, 35, 110029, tzinfo=utc)),
        ),
    ]
