# Generated by Django 3.0.5 on 2020-05-10 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0022_auto_20200510_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 15, 13, 41, 284849, tzinfo=utc)),
        ),
    ]
