# Generated by Django 3.0.5 on 2020-05-10 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dest', '0023_auto_20200510_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travel_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 17, 15, 14, 32, 413507, tzinfo=utc)),
        ),
    ]
